SAGEOctAcorde/SAGEOctAcorde/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^estacionamientos/', include('estacionamientos.urls'))
)

SAGEOctAcorde/estacionamientos/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from estacionamientos import views


# Este error es raro, en django funciona
urlpatterns = patterns('',
    url(r'^$', views.estacionamientos_all, name = 'estacionamientos_all'),
    url(r'^(?P<_id>\d+)/$', views.estacionamiento_detail, name = 'estacionamiento_detail'),
    url(r'^(?P<_id>\d+)/reserva$', views.estacionamiento_reserva, name = 'estacionamiento_reserva'),
    url(r'^(?P<id_est>\d+)/confirmar_reserva$', views.estacionamiento_confirmar_reserva, name = 'estacionamiento_confirmar_reserva'),
)

SAGEOctAcorde/estacionamientos/models.py
# -*- coding: utf-8 -*-

from django.core.validators import RegexValidator
from django.db import models
from django.forms import ModelForm
from _overlapped import NULL


class Estacionamiento(models.Model):
	# propietario=models.ForeignKey(Propietario)
	Propietario = models.CharField(max_length = 50, help_text = "Nombre Propio")
	Nombre = models.CharField(max_length = 50)
	Direccion = models.TextField(max_length = 120)

	Telefono_1 = models.CharField(blank = True, null = True, max_length = 30)
	Telefono_2 = models.CharField(blank = True, null = True, max_length = 30)
	Telefono_3 = models.CharField(blank = True, null = True, max_length = 30)

	Email_1 = models.EmailField(blank = True, null = True)
	Email_2 = models.EmailField(blank = True, null = True)

	Rif = models.CharField(max_length = 12)

	Apertura = models.TimeField(blank = True, null = True)
	Cierre = models.TimeField(blank = True, null = True)
	Reservas_Inicio = models.TimeField(blank = True, null = True)
	Reservas_Cierre = models.TimeField(blank = True, null = True)
	NroPuesto = models.IntegerField(blank = True, null = True)
	Tarifa = models.ForeignKey('Tarifa', null = True, blank = True)


class ReservasModel(models.Model):
	Estacionamiento = models.ForeignKey(Estacionamiento)
	fecha_inicio  = models.DateTimeField()
	InicioReserva = models.TimeField()
	fecha_final  = models.DateTimeField()
	FinalReserva = models.TimeField()

class Tarifa(models.Model):
	tipo_granularidad = (("min","Minutos"), ("hrs","Horas"),)
	
	nombre = models.CharField(max_length= 25)
	tarifa = models.DecimalField( max_digits = 10, decimal_places=2 )
	granularidad = models.CharField(default = "hrs", max_length = 4, choices = tipo_granularidad, blank = False)
	
	def __str__(self):              # __unicode__ on Python 2
		return str(self.nombre)

SAGEOctAcorde/estacionamientos/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.forms import ModelForm
from estacionamientos.models import *
from django.core.validators import RegexValidator
from django.template.defaultfilters import default


class EstacionamientoForm(forms.Form):

    phone_validator = RegexValidator(
                            regex = '^((0212)|(0412)|(0416)|(0414)|(0424)|(0426))-?\d{7}',
                            message = 'Debe introducir un formato válido.'
                        )

    # nombre del dueno (no se permiten digitos)
    propietario = forms.CharField(
                    required = True,
                    label = "Propietario",
                    validators = [
                          RegexValidator(
                                regex = '^[a-zA-ZáéíóúñÑÁÉÍÓÚ ]+$',
                                message = 'Sólo debe contener letras.'
                        )
                    ],
                    help_text="Nombre del propietario del estacionamiento."
                )

    nombre = forms.CharField(required = True, label = "Nombre",
                    help_text="Nombre del estacionamiento.")

    direccion = forms.CharField(required = True,
                    help_text="Dirección del estacionamiento.")

    telefono_1 = forms.CharField(required = False, validators = [phone_validator],
                    help_text="Telefono de contacto. Ejemplo : 0426-1234567")
    telefono_2 = forms.CharField(required = False, validators = [phone_validator],
                    help_text="Telefono de contacto. Ejemplo : 0426-1234567")
    telefono_3 = forms.CharField(required = False, validators = [phone_validator],
                    help_text="Telefono de contacto. Ejemplo : 0426-1234567")

    email_1 = forms.EmailField(required = False,
                    help_text="Correo de contacto. Ejemplo : octacorde@gmail.com")
    email_2 = forms.EmailField(required = False,
                    help_text="Correo de contacto. Ejemplo : octacorde@gmail.com")

    rif = forms.CharField(
                    required = True,
                    label = "RIF",
                    validators = [
                          RegexValidator(
                                regex = '^[JVD]-?\d{8}-?\d$',
                                message = 'Introduzca un RIF con un formato válido.'
                        )
                    ],
                    help_text="Rif del estacionamiento. Ejemplo : J-00000000-0"
                )

class EstacionamientoExtendedForm(ModelForm):
    Tarifa = forms.ModelChoiceField(
        queryset=Tarifa.objects.all(), 
        empty_label="Seleccione tipo de Tarifa",
        required = True
        )

    monto = forms.DecimalField( max_digits = 10, decimal_places=2,
                                 label = 'Monto', required = False)
    
    class Meta:
        model = Estacionamiento
        exclude = ['Propietario','Nombre','Direccion', 'Telefono_1', 'Telefono_2','Telefono_3',
                    'Email_1','Email_2','Rif', 'Tarifa']


class EstacionamientoReserva(forms.Form):
    f_inicio = forms.DateTimeField(label='Fecha inicio',\
                             help_text="Fecha de inicio de la reserva. Ejemplo : 13:01")
    inicio = forms.TimeField(label = 'Horario de inicio',\
                             help_text="Hora de inicio de la reserva en formato militar. Ejemplo : 13:01")
    f_final = forms.DateTimeField(label='Fecha final',\
                             help_text="Fecha final de la reserva. Ejemplo : 13:01")
    final = forms.TimeField(label = 'Horario final',\
                             help_text="Hora final de la reserva en formato militar. Ejemplo : 14:01")

class DefinirTarifa(ModelForm):
    class Meta:
        model = Tarifa
        exclude = ['nombre']

SAGEOctAcorde/estacionamientos/controller.py
# -*- coding: utf-8 -*-

# Archivo con funciones de control para SAGE
import functools
import datetime
from _decimal import Decimal


def validarHorarioEstacionamiento(aperturaEst, finalEst, inicioReservaEst, finalReservaEst):
	'''
		Chequea que el horario de estacionamiento de apertura y el horario de apertura 
		de las reservas esten correctos.
		
	'''
	if aperturaEst >= finalEst:
		return (False, 'El horario de apertura debe ser menor al horario de cierre')
	if inicioReservaEst >= finalReservaEst:
		return (False, 'El horario de inicio de reserva debe ser menor al horario de cierre')
	if inicioReservaEst < aperturaEst:
		return (False, 'El horario de inicio de reserva debe ser mayor o igual al horario de apertura del estacionamiento')
	if inicioReservaEst > finalEst:
		return (False, 'El horario de comienzo de reserva debe ser menor al horario de cierre del estacionamiento')
	if finalReservaEst < aperturaEst:
		return (False, 'El horario de apertura del estacionamiento debe ser menor al horario de finalización de las reservas')
	if finalReservaEst > finalEst:
		return (False, 'El horario de cierre del estacionamiento debe ser mayor o igual al horario de finalización de las reservas')
	
	return (True, '')

def validarHorarioReserva(inicioReserva, finalReserva, aperturaReservaEst, cierreReservaEst):
	'''
		Chequea que el horario de la reserva sea correcta considerando el horario de apertura de las reservas
		del estacionamiento.
	'''
	if inicioReserva >= finalReserva:
		return (False, 'El horario de apertura debe ser menor al horario de cierre')
	if finalReserva.hour - inicioReserva.hour < 1:
		return (False, 'El tiempo de reserva debe ser al menos de 1 hora')
	if finalReserva > cierreReservaEst:
		return (False, 'El horario de cierre de reserva debe estar en un horario válido')
	if inicioReserva < aperturaReservaEst:
		return (False, 'El horario de inicio de reserva debe estar en un horario válido')
	
	return (True, '')


def compararTuplasMarzullo(tupla1, tupla2):
	'Si tupla1 > tupla2 retorna 1; sino -1'
	
	if tupla1[0] > tupla2[0]: return 1
	if tupla1[0] < tupla2[0]: return -1

	if tupla1[1] >= tupla2[1]: return -1

	return 1

def interseccion(A_inicio,A_final,B_inicio,B_final):
	''' 
	    Funcion que dado dos intervalos (a1,b1),(a2,b2).
	    Indica si existe interseccion entre éllos.
    '''
	inicioMasLargo = max(A_inicio, B_inicio)
	finalMasCorto  = min(A_final, B_final)
	return inicioMasLargo < finalMasCorto

def calculoPrecio(hin, hout, tarifa):
	fchcomienzo = datetime.timedelta(hours=hout.hour,minutes=hout.minute)
	fchfinal = datetime.timedelta(hours=hin.hour,minutes=hin.minute)
	tiempoTotal = fchcomienzo - fchfinal
	tt_secs = Decimal(tiempoTotal.total_seconds())
	if(tarifa.granularidad == "hrs"):
		pago = tt_secs // 3600 * tarifa.tarifa
		if tt_secs % 3600 != 0:
			pago+= tarifa.tarifa
		return pago
	else:
		pago = (tt_secs // 60) * (tarifa.tarifa / 60)
		return pago

def puedeReservarALas(horaIni,horaFin,capacidad,reservas):
	'Verifica usando Marzullo si una reserva esta disponible'
	tablaMarzullo = crearTablaMarzullo(reservas)
	tablaMarzullo.sort(key=functools.cmp_to_key(compararTuplasMarzullo))
	
	best, beststart, bestend, cnt = 0,0,0,0
	for i in range(0, len(tablaMarzullo)-1):
		cnt = cnt - tablaMarzullo[i][1]
	
		if cnt >= best:
			best, beststart  = cnt, tablaMarzullo[i][0]
			bestend = tablaMarzullo[i + 1][0]
			
		if tablaMarzullo[i][0] >= horaFin: return True
		
		if (cnt == capacidad) and \
			interseccion(horaIni, horaFin, beststart, bestend):
			return False
		
	return True

def timeDesdeCadena(timeCad):
	'Funcion que dado una fecha en formato string, devuelve una instancia de Time'
	return datetime.datetime.strptime(timeCad, "%H:%M") # "%Y-%m-%d %H:%M" formato para fechas

def crearTuplasHorasDesdeListaCadena(listaTuplas):
	'''
	Convierte tuplas de string a time
	'''
	listaHora = []

	for tupla in listaTuplas:
		listaHora.append( (timeDesdeCadena(tupla[0]),timeDesdeCadena(tupla[1])) )
	
	return listaHora
				


def crearTablaMarzullo(reservas):
	''' Funcion que dada una lista de reservaciones, devuelve 
		la tabla(lista) ordenada asociada al algoritmo de Marzullo'''
	
	listaTuplas = []
	
	for elemReserva in reservas:
		listaTuplas.append((elemReserva[0], -1))
		listaTuplas.append((elemReserva[1],  1))

	return listaTuplas


#===============================================================================
# ACTUALIZAR CUANDO SE TOME COMO MAXIMO 7 DIAS
#===============================================================================
def calcularDuracion(t_inicio,t_final):
	'Regresa la diferencia entre dos time'
	#dia_inicial = int(t_inicio.strftime('%d'))
	hora_inicial = int(t_inicio.strftime(r'%H'))
	min_inicial = int(t_inicio.strftime(r'%M')) + hora_inicial * 60

	#dia_final = int(t_final.strftime('%d'))
	hora_final = int(t_final.strftime(r'%H'))
	min_final = int(t_final.strftime(r'%M'))  + hora_final * 60
	
	tt_mins = min_final - min_inicial
	tt_horas = tt_mins // 60
	tt_mins -= tt_horas * 60
	
	return (tt_horas,tt_mins)
	
def cadena_duracion(horas , minutos):
	'Regresa una cadena de la forma : 3 Horas y 25 minutos. '

	cadena = ""
	if horas > 0:
		cadena +=  "%d Hora" % horas
		if horas > 1:
			cadena += "s"
			
		if minutos > 0:
			cadena += " y "
			

	if minutos > 0:
		cadena +=  "%d Minuto" % minutos
		if minutos > 1:
			cadena +=  "s"
			
	cadena += "."
	
	return cadena

SAGEOctAcorde/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es"><head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    
    <meta charset="utf-8">
    <title>
      SAGE
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/base.css'%}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet">
    
   </head>
    
    <!-- Header -->
    <div id="top-nav" class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-toggle">
            </span>
          </button>
          <div class="navbar-brand" href="#">
            SAGE
          </div>
        </div>
        <div class="navbar-collapse collapse">
          
        </div>
      </div>
      <!-- /container -->
    </div>
    <!-- /Header -->
    
    <!-- Main -->
    <div class="container">
      
      <!-- upper section -->
      <div class="row">
        <div class="col-sm-2">
          <!-- left -->
          <h3>
            <i class="glyphicon glyphicon-briefcase">
            </i>
            Menú
          </h3>
          <hr>
          
          <ul class="nav nav-stacked">
            <li>
              <a href=".">
                <i class="fa fa-bus"></i>
                Estacionamientos
              </a>
            </li>
          </ul>          
          <hr>
          
        </div>
        <!-- /span-3 -->
<div class="col-sm-10">
        
      <!-- column 2 --> 
       <h3><i class="fa fa-bus"></i> Estacionamientos</h3>  
            
       <hr>
      
     <div class="row">
            <!-- center left--> 
          <!--/col-->
         
            <!--center-right-->
          <!--/col-span-6-->
     
       <div class="col-md-8"> 
      <table class="table table-striped">
      {% if estacionamientos %}

        <thead>
          <tr><th></th><th>Dueño</th><th>Nombre</th><th>RIF</th></tr>
        </thead>
        <tbody>
        {% for obj in estacionamientos %}
          <tr><td>{{forloop.counter}}</td><td>{{obj.Propietario}}</td><td>{{obj.Nombre}}</td><td>{{obj.Rif}}</td><td><a href="./{{obj.id}}"><i class="fa fa-search"></i></a> </td></tr>
        {% endfor %}
        </tbody>
        {% else %}
       <h3>No hay estacionamientos</h3>
      {% endif %}
      </table>
      <hr>              
    </div><div class="col-md-4">

    
          <div class="panel panel-default">
            <div class="panel-heading">
              <div class="panel-title">
                <i class="glyphicon glyphicon-wrench pull-right">
                </i>
                <h4>
                  Crear estacionamiento
                </h4>
              </div>
            </div>
            <div class="panel-body">

      
              
              <form action="." method="post" class="form form-vertical">
              {% csrf_token %}
              {%include "form_validacion.html" %}                
                <div class="control-group">
                  <label>
                  </label>
                  <div class="controls">
                    <button type="submit" class="btn btn-primary">
                      Crear estacionamiento
                    </button>
                  </div>
                </div>
                
                
              </form>
              
              
            </div>
            <!--/panel content-->
          </div>
          <!--/panel-->
          
          <!--/panel-->
          
        </div></div><!--/row-->
    </div>
        
      </div>
      <!--/row-->
      <!-- /upper section -->
      
      <!-- lower section -->
      <div class="row">
      </div>
      <!--/row-->
      
    </div>
    <!--/container-->

    <script type="text/javascript" src="{% static 'js/jquery-2.1.1.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
</body></html>

SAGEOctAcorde/templates/estacionamientoConfirReserva.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es"><head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    
    <meta charset="utf-8">
    <title>
      SAGE
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/base.css'%}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet">
    
   </head>

 <body>
        
        <!-- Header -->
<div id="top-nav" class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-toggle"></span>
      </button>
          <div class="navbar-brand" href="#">
            SAGE
          </div>
    </div>
  </div><!-- /container -->
</div>
<!-- /Header -->

<!-- Main -->
<div class="container">
  
  <!-- upper section -->
  <div class="row">
  <div class="col-sm-2">
      <!-- left -->
                <h3>
            <i class="glyphicon glyphicon-briefcase">
            </i>
            Menú
          </h3>
      <hr>

         <ul class="nav nav-stacked">
            <li>
              <a href="..">
                <i class="fa fa-bus"></i>
                Estacionamientos
              </a>
            </li>
          </ul>

          <br>
          {% if estacionamiento.NroPuesto %}
            <ul class="nav nav-stacked">
              <li>
                <a href="./reserva">
                  <i class="fa fa-pencil-square-o"></i>
                  Reservar
                </a>
              </li>
            </ul>
          {% endif %}
      <hr>
      
    </div><!-- /span-3 -->
    <div class="col-md-4">
      
      <table class="table table-striped">
        <thead>
        </thead>
        <tbody>
		    <hr>
			<tr><td class="active" colspan= 2><b><i class="glyphicon glyphicon-info-sign"></i> Datos de la reserva:</b></td></tr>          	
			<tr>
				<td><b><i class="glyphicon glyphicon-time"></i> Inicio:</b></td>
				<td><b>{{hora_inicio}}</b></td>

			</tr>
			<tr>
				<td><b><i class="glyphicon glyphicon-time"></i> Fin:</b></td>
				<td><b>{{hora_final}}</b></td>
			</tr>
			<tr>
				<td><b><i class="glyphicon glyphicon-time"></i> Duraci&oacuten:</b></td>
				<td><b>{{duracion}} </b></td>
			</tr>
			<tr>
				{% if precio %}
					<td><b><i class="fa fa-money"></i> Costo:</b></td>
					<td><b>{{precio}} Bs. </b></td>
				</tr>
	           <tr class = "alert alert-success">
	           {% else %}
				</tr>
	           <tr class = "alert alert-danger">
				{% endif %}
	           	<td  colspan= 2>
	           		<i class="col-md-8" style="color:{{color}};" > {{mensaje}} </i>
	           	</td>
           	</tr>

	        </tbody>
	      </table>
			
            <div class="control-group">
              <label>
              </label>
              <div class="controls">
					<form action="./confirmar_reserva" method="post" >
		             {% csrf_token %}
						<input type="hidden" name="inicio" value="{{hora_inicio}}"  for='id_inicio'>
						<input type="hidden" name="final" value="{{hora_final}}"   for='id_final'>
						
			          {% if precio %}
							<button class="btn btn-primary" type='submit' onclick = "alert('Pago realizado con exito!')">
			                  Reservar
			                </button>			           
				            <button type = "button" class="btn btn-primary" onClick=" window.location.href='';alert('Reserva cancelada!')">
			           {%else%}
				            <button type = "button" class="btn btn-primary" onClick=" window.location.href=''">
			           {% endif %}
				              Cancelar
				            </button>
					</form>
		      
                
              </div>
            </div>
      		          	
      
      <hr>  
      
    </div>
          
        </div><!--/col-span-9-->
    
  </div><!--/row-->
  <!-- /upper section -->
  
  <!-- lower section -->
  <!--/row-->

</div><!--/container-->


    <script type="text/javascript" src="{% static 'js/jquery-2.1.1.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>

</body>

</html>

SAGEOctAcorde/templates/estacionamientoReserva.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es"><head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    
    <meta charset="utf-8">
    <title>
      SAGE
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/base.css'%}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet">
   </head>
 <body>
        
        <!-- Header -->
<div id="top-nav" class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-toggle"></span>
      </button>
          <div class="navbar-brand" href="#">
            SAGE
          </div>
    </div>
  </div><!-- /container -->
</div>
<!-- /Header -->

<!-- Main -->
<div class="container">
  
  <!-- upper section -->
  <div class="row">
  <div class="col-sm-2">
      <!-- left -->
                <h3>
            <i class="glyphicon glyphicon-briefcase">
            </i>
            Menú
          </h3>
      <hr>

         <ul class="nav nav-stacked">
            <li>
              <a href="..">
                <i class="fa fa-bus"></i>
                Estacionamientos
              </a>
            </li>
          </ul>
          <br>
          <ul class="nav nav-stacked">
            <li>
              <a href="./reserva">
                <i class="fa fa-pencil-square-o"></i>
                Reservar
              </a>
            </li>
          </ul>
      <hr>
      
    </div><!-- /span-3 -->
    <div class="col-sm-9">
        
      <!-- column 2 --> 
       <h3><i class="fa fa-bus"></i> Estacionamiento {{estacionamiento.Nombre}}</h3>  
            
       <hr>
      
     <!--/row-->
    <div class="col-md-4">
      
      <table class="table table-striped">
        <thead>
          
        </thead>
        <tbody>
			<tr><td><b><i class="fa fa-car"></i> Nombre del estacionamiento:</b></td></tr>
      <tr><td>{{estacionamiento.Nombre}}</td></tr>

      <tr><td><b><i class="fa fa-user"></i> Nombre del propietario:</b></td></tr>
      <tr><td>{{estacionamiento.Propietario}}</td></tr>

      <tr><td><b><i class="fa fa-home"></i> Dirección:</b></td></tr>
      <tr><td>{{estacionamiento.Direccion}}</td></tr>

      {% if estacionamiento.Telefono_1 %}
        <tr><td><b><i class="fa fa-phone"></i> Teléfono:</b></td></tr>
        <tr><td>{{estacionamiento.Telefono_1}}</td></tr>
      {% endif %}

      {% if estacionamiento.Telefono_2 %}
        <tr><td><b><i class="fa fa-phone"></i> Teléfono:</b></td></tr>
        <tr><td>{{estacionamiento.Telefono_2}}</td></tr>
      {% endif %}

       {% if estacionamiento.Telefono_3 %}
        <tr><td><b><i class="fa fa-phone"></i> Teléfono:</b></td></tr>
        <tr><td>{{estacionamiento.Telefono_3}}</td></tr>
      {% endif %}

      {% if estacionamiento.Email_1 %}
        <tr><td><b><i class="fa fa-at"></i> Correo Electrónico:</b></td></tr>
        <tr><td>{{estacionamiento.Email_1}}</td></tr>
      {% endif %}

      {% if estacionamiento.Email_2 %}
      <tr><td><b><i class="fa fa-at"></i> Correo Electrónico:</b></td></tr>
      <tr><td>{{estacionamiento.Email_2}}</td></tr>
      {% endif %}


      <tr><td><b><i class="fa fa-circle"></i> RIF:</b></td></tr>
      <tr><td>{{estacionamiento.Rif}}</td></tr>
          
        </tbody>
      </table>
      
      <hr>  
      <hr>
      
   

    
    </div>
    <div class="col-md-4">
       
       <table class="table table-striped">
        <thead>
          
        </thead>
        <tbody>
      {% if estacionamiento.NroPuesto %}
        <tr><td><b><i class="fa fa-car"></i> Puestos:</b></td></tr>
        <tr><td>{{estacionamiento.NroPuesto}}</td></tr>
      {% endif %}
      {% if estacionamiento.Reservas_Inicio %}
        <tr><td><b><i class="fa fa-clock-o"></i> Horario inicio de reserva:</b></td></tr>
        <tr><td>{{estacionamiento.Reservas_Inicio}}</td></tr>
      {% endif %}
      {% if estacionamiento.Reservas_Cierre %}
        <tr><td><b><i class="fa fa-clock-o"></i> Horario fin de reserva:</b></td></tr>
        <tr><td>{{estacionamiento.Reservas_Cierre}}</td></tr>
      {% endif %}
      {% if estacionamiento.Apertura %}
        <tr><td><b><i class="fa fa-clock-o"></i> Horario apertura:</b></td></tr>
        <tr><td>{{estacionamiento.Apertura}}</td></tr>
      {% endif %}
      {% if estacionamiento.Cierre %}
        <tr><td><b><i class="fa fa-clock-o"></i> Horario cierre:</b></td></tr>
        <tr><td>{{estacionamiento.Cierre}}</td></tr>
      {% endif %}
    {% if estacionamiento.Tarifa %}
        <tr><td><b><i class="fa fa-money"></i></i> Tipo de Cobro:</b></td></tr>
        <tr><td>{{estacionamiento.Tarifa}}</td></tr>
        <tr><td><b><i class="fa fa-money"></i></i> Tarifa:</b></td></tr>
        <tr><td>{{estacionamiento.Tarifa.tarifa}} Bsf.</td></tr>
      {% endif %}
      
      
        </tbody>
      </table>
    </div><div class="col-md-4">

    
          <div class="panel panel-default">
            <div class="panel-heading">
              <div class="panel-title">
                <i class="glyphicon glyphicon-wrench pull-right">
                </i>
                <h4>
                  Reserva
                </h4>
              </div>
            </div>
            <div class="panel-body">


              <form action="./reserva" method="post" class="form form-vertical">
              {% csrf_token %}
              {%include "form_validacion.html" %}
                <div class="control-group">
                  <label>
                  </label>
                  <div class="controls">
                    <button type="submit" class="btn btn-primary">
                      Chequear Disponibilidad
                    </button>
                  </div>
                </div>
              </form>
              
              
            </div>

            <!--/panel content-->
          </div>
          <!--/panel-->
          
          <!--/panel-->
          
        </div><!--/col-span-9-->
    
  </div><!--/row-->
  <!-- /upper section -->
  
  <!-- lower section -->
  <!--/row-->

</div><!--/container-->
<!-- /Main -->
<br><br><br><br>



    <script type="text/javascript" src="{% static 'js/jquery-2.1.1.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.-collapse.js'%}"></script>

</body>

</html>